chat/urls.py
from django.urls import path
from .views import index, login_view, register, addcontact, logout_view, profile, edit

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('addcontact/', addcontact, name='newcontact'),
    path('profile/<str:username>', profile, name='profile'),
    path('edit/', edit, name='edit')
]

chatproject/urls.py
from django.contrib import admin
from django.urls import path, include

from chat.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
]

chat/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

deafult_receiver = 1

class User(AbstractUser):
    email = models.EmailField(max_length=254)
    gender = models.CharField(max_length=1)
    dob = models.DateField()
    age = models.PositiveSmallIntegerField()
    status = models.TextField(max_length=150)
    avatar = models.URLField(max_length=250)

    def serialize(self):
        return {
            "username": self.username,
            "avatar": self.avatar,
            "timestamp": self.last_login,
        }

class Message(models.Model):
    sender = models.ForeignKey(User, related_name='author_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Message from {self.sender.username} to {self.receiver.username}'

    def last_10_messages():
        return Message.objects.order_by('-timestamp').all()[:10]

class Contacts(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='person')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friends')

    def __str__(self):
        return f'{self.user1.username} is in contact with {self.user2.username}'

chat/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse, HttpResponseRedirect, render
from django.urls import reverse
from django.http import JsonResponse
from django.utils.safestring import mark_safe
from django.views.decorators.csrf import csrf_exempt
from django.db import IntegrityError
import json

from .models import User, Contacts

def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            return render(request, "chat/login.html", {
                "message": "Invalid username and/or password."
            })

    else:
        logout(request)
        return render(request, "chat/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login')


def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST["email"]
        gender = request.POST["gender"]
        dob = request.POST["dob"]
        age = request.POST["age"]
        status = request.POST["status"]
        if status == "":
            status = "Hey there, I am using Chaticon"
        avatar = request.POST["avatar-link"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        # Ensure password matches confirmation
        if password != confirmation:
            return render(request, "chat/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(
                username = username,
                email = email,
                gender = gender,
                dob = dob,
                age = age,
                status = status,
                avatar = avatar,
                password=password
            )
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, "chat/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect('/')

    else:
        return render(request, "chat/register.html")


@login_required(login_url='login/')
def index(request):
    contacts = Contacts.objects.filter(user1=request.user)

    contact_list = list()
    for contact in contacts:
        contact_list.append(contact.user2)

    return render(request, 'chat/room.html', {
        'username': mark_safe(json.dumps(request.user.username)),
        'user': request.user,
        'contacts': contacts
    })


@csrf_exempt
@login_required(login_url='login/')
def addcontact(request):

    #  If POST request
    if request.method == "POST":
        logged_user = request.user

        data = json.loads(request.body)
        addContacts = data.get("newcontacts")

        if not addContacts:
            return JsonResponse({"message": "No Contacts Added."}, status=201)
        else:
            n = 0
            for contact_name in addContacts:
                contact = User()
                contact = User.objects.get(username=contact_name)
                c1 = Contacts(user1=logged_user, user2=contact)
                c1.save()
                c2 = Contacts(user1=contact, user2=logged_user)
                c2.save()
                n = n + 1
            return JsonResponse({"message": f"{n} Contacts Added Successfully."}, status=201)

    # If GET request
    else:
        contacts = Contacts.objects.filter(user1=request.user)
        contacts_list = list()
        for contact in contacts:
            contacts_list.append(contact.user2)

        all_contacts = User.objects.exclude(username=request.user)

        new_contacts = list()
        for contact in all_contacts:
            if contact not in contacts_list:
                new_contacts.append(contact)

        # If no new users are there to be added
        if not new_contacts:
                return render(request, 'chat/addcontact.html', {
                'username': mark_safe(json.dumps(request.user.username)),
                'allcontacts': "No Users Available"
            })
        # If new users can be added
        else:
            return render(request, 'chat/addcontact.html', {
                'username': mark_safe(json.dumps(request.user.username)),
                'allcontacts': new_contacts
            })


@login_required(login_url='login/')
def profile(request, username):
    logged_user = request.user
    user = User.objects.get(username=username)
    return render(request, 'chat/profile.html', {
        'logged_user': logged_user,
        'user': user
    })


@login_required(login_url='login/')
def edit(request):
    #  If POST request
    if request.method == "POST":
        email = request.POST["email"]
        gender = request.POST["gender"]
        age = request.POST["age"]
        status = request.POST["status"]
        if status == "":
            status = "Hey there, I am using Chaticon"
        avatar = request.POST["avatar-link"]

        # Attempt to edit user
        try:
            user = User.objects.get(username=request.user)
            user.email = email
            user.gender = gender
            user.age = age
            user.status = status
            user.avatar = avatar
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, "chat/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect('/')

    #  If GET request
    else:
        logged_user = request.user
        return render(request, 'chat/edit.html', {
            'user': logged_user
        })

chat/templates/chat/addcontact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel='stylesheet prefetch' href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/chatlogo.png' %}" type="image/x-icon">
    <title>Add Contact</title>
</head>
<body class="form-body">

    {% if allcontacts == "No Users Available" %}
        <h3>No Users Available<h3>
        <button class="form-button" id="goback" onclick="location.href='/';">Go Back</button>
    {% else %}
        <div class="form-div">
            {% for contact in allcontacts %}
                <label class="checkbox-container">{{ contact.username }}
                    <input class="form-field" type="checkbox" name="new_contact" value="{{ contact.username }}">
                    <span class="checkmark"></span>
                </label>
            {% endfor %}
            <br>
            <button class="addcontact-page-button form-button" id="add_contacts">Add Contacts</button>
            <button class="addcontact-page-button form-button" id="goback" onclick="location.href='/';">Back</button>
        </div>

    {% endif %}

    <script>

        var newContacts = []

        function getSelectedContacts(){
            var checkedboxes = document.querySelectorAll('input[type=checkbox]:checked');
            for (var i = 0; i < checkedboxes.length; i++) {
                newContacts.push(checkedboxes[i].value);
            }
        }

        function addContacts(){
            fetch('/addcontact/', {
                method: 'POST',
                body: JSON.stringify({
                    newcontacts: newContacts
                })
            })
            .then(response => response.json())
            .then(result => {
                // Print result
                console.log(result);

                if (result.message == "No Contacts Added."){
                    alert("No Contacts Selected.");
                }
                else{
                    alert(result.message);
                    window.location.replace("/");
                }
            })
            .catch(error => {
                console.log(error);
                alert(`Error: ${error}`);
            });

        }

        // On clicking "Add Contacts" button
        document.querySelector('#add_contacts').addEventListener('click', (event) => {
            getSelectedContacts();
            addContacts();
        });

    </script>

</body>
</html>

chat/templates/chat/edit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel='stylesheet prefetch' href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/chatlogo.png' %}" type="image/x-icon">
    <title>Edit Profile</title>
</head>
<body class="form-body">

    {% if message %}
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function() {
                alert("{{message}}");
            })
        </script>
    {% endif %}

    <div class="form-div">
        <div class="form-header">
            <img class="form-header-image" id="letter-avatar" src="{{ user.avatar }}">
            <h2 class="form-header-title">{{user.username}}</h2>
        </div>
        <form id="registration-form" action="{% url 'chat:edit' %}" method="post">
            {% csrf_token %}
            <input class="form-field form-input" type="email" name="email" placeholder="{{user.email}}" value="{{user.email}}" required>
            <br>

            <input class="form-field form-input avatar" type="text" id="abbreviation" name="abbreviation" maxlength="3" style="text-transform:uppercase" placeholder="{{user.avatar}}">
            <br>
            <!-- <label for="backgroundcolor">Background Colour:</label> -->
            <input type="color" class="avatar" id="backgroundcolor" name="backgroundcolor" value="#ffffff">
            <!-- <br> -->
            <!-- <label for="foregroundcolor">Foreground Colour:</label> -->
            <input type="color" class="avatar" id="foregroundcolor" name="foregroundcolor" value="#ffffff"><br>
            <!-- <img id="letter-avatar" src=""> -->
            <input type="text" id="avatar-link" name="avatar-link" value="{{user.avatar}}" hidden>
            <br>

            <div class="select-wrap form-field">
                <label>Gender</label>
                <select id="gender" name="gender" style="width: 100%;">
                {% if user.gender == 'M' %}
                    <option value="M" selected>Male</option>
                    <option value="F">Female</option>
                    <option value="O">Other</option>
                {% elif user.gender == 'F' %}
                    <option value="M">Male</option>
                    <option value="F" selected>Female</option>
                    <option value="O">Other</option>
                {% else %}
                    <option value="M">Male</option>
                    <option value="F">Female</option>
                    <option value="O" selected>Other</option>
                {% endif %}
                </select>
            </div>

            <input class="form-field form-input" type="number" id="age" name="age" placeholder="Age: {{user.age}}" value="{{user.age}}" required>
            <br>

            <input class="form-field form-input" type="text" id="status" name="status" placeholder="Status: {{user.status}}" value="{{user.status}}">
            <br>

            <input class="form-field form-input" id="password" type="password" name="password" placeholder="New Password">
            <br>
            <input class="form-field form-input" id="confirmation" type="password" name="confirmation" placeholder="Confirm New Password">
            <br>
            <input class="form-field form-button" type="submit" value="Save">
        </form>
        <br>
        <button class="form-field form-button" value="Cancel" onclick="location.href='/';">Cancel</button>
    </div>

    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
            const avatar_link = document.querySelector('#abbreviation').getAttribute('placeholder')
            const abbreviation = avatar_link.substring(avatar_link.indexOf("name")+5, avatar_link.indexOf("&background"))
            const backgroundcolor = avatar_link.substring(avatar_link.indexOf("background=")+11, avatar_link.indexOf("&color"))
            const foregroundcolor = avatar_link.substring(avatar_link.indexOf("color=")+6, avatar_link.indexOf("&length"))

            document.querySelector('#abbreviation').setAttribute('value', abbreviation)
            document.querySelector('#backgroundcolor').setAttribute('value', `#${backgroundcolor}`)
            document.querySelector('#foregroundcolor').setAttribute('value', `#${foregroundcolor}`)

            const avatars = document.querySelectorAll('.avatar');
            for (const avatar of avatars){
                avatar.addEventListener('change', (event) => {

                    var abbreviation = document.querySelector('#abbreviation').value;
                    abbreviation = abbreviation.toUpperCase();
                    var len = abbreviation.length;

                    var backgroundcolor = document.querySelector('#backgroundcolor').value;
                    backgroundcolor = backgroundcolor.replace("#","");

                    var foregroundcolor = document.querySelector('#foregroundcolor').value;
                    foregroundcolor = foregroundcolor.replace("#","");

                    var link = `https://ui-avatars.com/api/?name=${abbreviation}&background=${backgroundcolor}&color=${foregroundcolor}&length=${len}&rounded=true`;
                    document.querySelector("#letter-avatar").setAttribute("src", link)
                    document.querySelector("#avatar-link").value = link

                });
            }
        })
    </script>

</body>
</html>

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/login.html
{% load static %}
<!-- chat/templates/chat/login.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel='stylesheet prefetch' href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/chatlogo.png' %}" type="image/x-icon">
    <title>Login</title>
</head>
<body class="form-body">

    {% if message %}
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function() {
                alert("{{message}}");
            })
        </script>
    {% endif %}
    
    <div class="form-div">
        <div class="form-header">
            <img class="form-header-image" src="{% static 'images/chatlogo.png' %}">
            <h2 class="form-header-title">Chaticon</h2>
        </div>
        <form action="{% url 'chat:login' %}" method="post">
            {% csrf_token %}
            <input class="form-field form-input" autofocus name="username" placeholder="Username" required>
            <br>
            <input class="form-field form-input" type="password" name="password" placeholder="Password" required>
            <br>
            <input class="form-field form-button" type="submit" value="Login">
            <p class="form-text">Don't have an account? <a class="form-text" href="{% url 'chat:register' %}"><br>Register here.</a></p>
        </form>
    </div>

</body>
</html>

chat/templates/chat/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel='stylesheet prefetch' href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/chatlogo.png' %}" type="image/x-icon">
    <title>Profile: {{ user.username }}</title>
</head>
<body class="form-body">

    {% if message %}
        {{message}}
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function() {
                alert("{{message}}");
            })
        </script>
    {% endif %}

    <div class="form-div">
        <div class="form-header">
            <img class="form-header-image" id="letter-avatar" src="{{ user.avatar }}">
            <h2 class="form-header-title">{{user.username}}</h2>
        </div>
        <div>
            <h4 id="status-display">"{{user.status}}"</h4>
            {% if user.gender == 'M' %}
                <p><b>Gender:</b> Male</p>
            {% elif user.gender == 'F' %}
                <p><b>Gender:</b> Female</p>
            {% else %}
                <p><b>Gender:</b> Other</p>
            {% endif %}
            <p><b>Age:</b> {{user.age}}</p>
            <p><b>Date Of Birth:</b> {{user.dob}}</p>
            <p><b>Email:</b> {{user.email}}</p>

            <button class="form-field form-button" value="back" onclick="location.href='/';">Back</button>
            <br>

            {% if logged_user.username == user.username %}
                <button class="form-field form-button" value="edit" onclick="location.href='/edit';">Edit Profile</button>
            {% endif %}

        </div>
    </div>

</body>
</html>

chat/templates/chat/register.html
{% load static %}
<!-- chat/templates/chat/register.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel='stylesheet prefetch' href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/chatlogo.png' %}" type="image/x-icon">
    <title>Register</title>
</head>
<body class="form-body">

    {% if message %}
        {{message}}
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function() {
                alert("{{message}}");
            })
        </script>
    {% endif %}

    <div class="form-div">
        <div class="form-header">
            <img class="form-header-image" id="letter-avatar" src="{% static 'images/chatlogo.png' %}">
            <h2 class="form-header-title">Chaticon</h2>
        </div>
        <form id="registration-form" onsubmit="event.preventDefault(); validateForm();" action="{% url 'chat:register' %}" method="post">
            {% csrf_token %}
            <input autofocus class="form-field form-input" name="username" placeholder="Username" required>
            <br>
            <input class="form-field form-input" type="email" name="email" placeholder="Email Address" required>
            <br>

            <input class="form-field form-input avatar" type="text" id="abbreviation" name="abbreviation" maxlength="3" style="text-transform:uppercase" placeholder="Abbrevation">
            <br>
            <input type="color" class="avatar" id="backgroundcolor" name="backgroundcolor" value="#000000">
            <input type="color" class="avatar" id="foregroundcolor" name="foregroundcolor" value="#ffffff"><br>
            <input type="text" id="avatar-link" name="avatar-link" hidden>
            <br>

            <div class="select-wrap form-field">
                <label>Gender</label>
                <select id="gender" name="gender" style="width: 100%;">
                  <option value="" disabled selected>---</option>
                  <option value="M">Male</option>
                  <option value="F">Female</option>
                  <option value="O">Other</option>
                </select>
            </div>

            <label for="dob">Date Of Birth</label>
            <input class="form-field" type="date" id="dob" name="dob" required>
            <br>

            <input class="form-field form-input" type="number" id="age" name="age" placeholder="Age" required>
            <br>

            <input class="form-field form-input" type="text" id="status" name="status" placeholder="Status">
            <br>

            <input class="form-field form-input" type="password" name="password" placeholder="Password" required>
            <br>
            <input class="form-field form-input" type="password" name="confirmation" placeholder="Confirm Password" required>
            <br>

            <input class="form-field form-button" type="submit" value="Register">

            <p class="form-text">Already have an account? <a class="form-text" href="{% url 'chat:login' %}"><br>Log In here.</a></p>
        </form>
    </div>

    <script>
        function containsSpecialChars(str) {
                const specialChars = /[ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/;
                return specialChars.test(str);
        }

        function validateForm(){
            if (document.querySelector("#gender").value == ""){
                alert("Please select a gender");
                return False
            }
            else if (document.querySelector("#age").value < 16){
                alert("You must be atleast 16 years of age to use this platform");
                return False
            }
            else if (document.querySelector("#age").value > 100){
                alert("Invalid Age");
                return False
            }
            else if (containsSpecialChars(document.querySelector("#username").value)) {
                alert("Username cannot contain symbol or space");
            }
            else if(document.querySelector("#username").value.length < 3){
                alert("Username must be minimum 3 charaters");
            }
            else if(document.querySelector("#username").value.length > 11){
                alert("Username can be maximum 10 charaters");
            }
            else if(document.querySelector("#password").value.length < 7){
                alert("Length of password must be between 8 and 16 characters");
            }
            else if(document.querySelector("#password").value.length > 17){
                alert("Length of password must be between 8 and 16 characters");
            }
            else if(document.querySelector("#password").value != document.querySelector("#confirmation").value){
                alert("Passwords don't match");
            }
            else{
                document.querySelector("#registration-form").submit();
                return True
            }
        }

        // function validateForm(){
        //     if (document.querySelector("#gender").value == ""){
        //         alert("Please select a gender.");
        //         return False
        //     }
        //     else if (document.querySelector("#age").value < 16){
        //         alert("You must be atleast 16 years of age to use this platform");
        //         return False
        //     }
        //     else if (document.querySelector("#age").value > 100){
        //         alert("Invalid Age");
        //         return False
        //     }
        //     else{
        //         document.querySelector("#registration-form").submit();
        //         return True
        //     }
        // }
    </script>

    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
            const avatars = document.querySelectorAll('.avatar');
            for (const avatar of avatars){
                avatar.addEventListener('change', (event) => {

                    var abbreviation = document.querySelector('#abbreviation').value;
                    abbreviation = abbreviation.toUpperCase();
                    var len = abbreviation.length;

                    var backgroundcolor = document.querySelector('#backgroundcolor').value;
                    backgroundcolor = backgroundcolor.replace("#","");

                    var foregroundcolor = document.querySelector('#foregroundcolor').value;
                    foregroundcolor = foregroundcolor.replace("#","");

                    var link = `https://ui-avatars.com/api/?name=${abbreviation}&background=${backgroundcolor}&color=${foregroundcolor}&length=${len}&rounded=true`;
                    document.querySelector("#letter-avatar").setAttribute("src", link)
                    document.querySelector("#avatar-link").value = link

                });
            }
        })
    </script>

</body>
</html>

chat/templates/chat/roomold.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
</body>
<script src="{% static 'reconnecting-websocket.js' %}"></script>
<script>
    var roomName = {{ room_name_json }}
    // const roomName = JSON.parse(document.getElementById('room-name').textContent);

    const chatSocket = new ReconnectingWebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        document.querySelector('#chat-log').value += (data.message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'command': 'new_message'
        }));
        messageInputDom.value = '';
    };
</script>
</html>